### ISSUE TITLE
Major Speed Issues

### ISSUE THREAD

**Issue by kmuncie** [kmuncie/omnibus-reader#17]
We are getting a 30+ second Time To First Byte waiting period when making our API calls. 

Can we do anything to improve our __makeRequest function or better cache the responses?

**Comment by onebytegone** [comment]
The function in question can be found at: https://github.com/kmuncie/omnibus-reader/blob/2c4221ec2f7c0c08887831bc4c777aab2b84d6cc/app/js/fetcher.js#L72-L90

There does appear to be some caching built in already. However I doubt the cache is being persisted between page reloads. I would lean towards using `$.ajax` over the current `$.json`. That way the JSONP callback param is handled automatically and we might be able to use the default ajax caching.

**Comment by kmuncie** [comment]
MR #19 helped immensely and implemented much better caching. With these improvements it would seem any further ones can only be made on the API side. Closing ticket.
