### ISSUE TITLE
Verse Links go to 404 page

### ISSUE THREAD

**Issue by onebytegone** [kmuncie/omnibus-reader#7]
Clicking on any of the verse numbers will take you to a 404 page. e.g. Mr. 1:16 will go to: http://kmuncie.github.io/en/publications/bible/nwt/books/json/html/41001001-41001999?callback=jQuery21004453211345244199_1433807276616&_=1433807276620#v41001016

Ideally, having verse linking would be nice. For a start though, having the links keep you on the same page would be of help.

**Comment by kmuncie** [comment]
They no longer 404 but the anchor links need to be deep linkable... will create a new issue for that
